services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEBOT_API_TOKEN
      sync: false
      - key: FOMO_SITE
      sync: false
      - key: FOMO_TWITTER
      sync: false
      - key: FOMO_TELEGRAM
      sync: false
      - key: BOT_LINK
      sync: false
      - key: CHANNEL_ID
      sync: false
      - key: RECIPIENT_PUBLIC_KEY
      sync: false
      - key: FOMO_IMG
      sync: false
