services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEBOT_API_TOKEN
        fromSecret: TELEBOT_API_TOKEN
      - key: FOMO_SITE
        fromSecret: FOMO_SITE
      - key: FOMO_TWITTER
        fromSecret: FOMO_TWITTER
      - key: FOMO_TELEGRAM
        fromSecret: FOMO_TELEGRAM
      - key: BOT_LINK
        fromSecret: BOT_LINK
      - key: CHANNEL_ID
        fromSecret: CHANNEL_ID
      - key: RECIPIENT_PUBLIC_KEY
        fromSecret: RECIPIENT_PUBLIC_KEY
      - key: FOMO_IMG
        fromSecret: FOMO_IMG
